package com.app.finance.domain.model

/**
 * The enumerations from 03-database-design.md §3.
 *
 * Every one is stored as an `INTEGER`, not text — smaller rows, faster
 * comparisons, no collation concerns. The [code] values are part of the on-disk
 * format and are matched by `CHECK` constraints in [com.app.finance.data.db.Schema];
 * they may be appended to but never renumbered.
 */

/** `income_kind` — 0 = Stable, 1 = Variable. */
enum class IncomeKind(val code: Int) {
    /** Salary and anything else that arrives on a predictable rhythm. */
    STABLE(0),

    /**
     * Farming, property, freelance — income that arrives in bursts.
     *
     * This is the default (the column's `DEFAULT 1`) because classifying a new
     * source as stable when it is not overstates the coverage figure the income
     * screen exists to report. Understating it is the safe direction.
     */
    VARIABLE(1),
    ;

    companion object {
        fun fromCode(code: Int): IncomeKind = entries.firstOrNull { it.code == code }
            ?: error("unknown income_kind: $code")
    }
}

/**
 * `nature` — 0 = Fixed, 1 = Variable, 2 = Unpredictable.
 *
 * Set on a root category and inherited by its children, which cannot override
 * it (FR-CAT-06). The split is what makes the safe-to-spend figure meaningful:
 * only variable and unpredictable spending is a decision the user can still
 * make this month.
 */
enum class Nature(val code: Int) {
    /** Rent, utilities, school fees — committed before the month starts. */
    FIXED(0),

    /** Groceries, transport, eating out — discretionary, and the daily figure. */
    VARIABLE(1),

    /** Medical, repairs, gifts — real, but not plannable month to month. */
    UNPREDICTABLE(2),
    ;

    /** Whether spending here still counts as a decision the user can make today. */
    val isDiscretionary: Boolean get() = this != FIXED

    companion object {
        fun fromCode(code: Int): Nature = entries.firstOrNull { it.code == code }
            ?: error("unknown nature: $code")
    }
}

/**
 * `payment_method` — 0 = Cash, 1 = bKash, 2 = Nagad, 3 = Bank, 4 = Card,
 * 5 = Other.
 *
 * FR-EXP-05 lists the first five; the database enum in 03 §3 adds `Other`, and
 * the wider set is used here so that stored data can never fall outside the
 * `CHECK` constraint.
 *
 * No display label lives here. "bKash" and "Nagad" are proper nouns and will
 * not change, but "Cash", "Bank" and "Card" are ordinary words that a Bengali
 * build has to translate — and this enum sits in `domain/`, which the
 * architecture check forbids from importing Android at all. The label lookup is
 * in the UI layer, in `PaymentMethodLabels.kt`.
 */
enum class PaymentMethod(val code: Int) {
    CASH(0),
    BKASH(1),
    NAGAD(2),
    BANK(3),
    CARD(4),
    OTHER(5),
    ;

    companion object {
        val DEFAULT = CASH

        /**
         * The five FR-EXP-05 names the user picks from. `OTHER` exists so the
         * database `CHECK` can never be violated by imported data, but it is
         * not offered in the picker.
         */
        val SELECTABLE = listOf(CASH, BKASH, NAGAD, BANK, CARD)

        fun fromCode(code: Int): PaymentMethod = entries.firstOrNull { it.code == code }
            ?: error("unknown payment_method: $code")
    }
}

/** `entry_status` — 0 = Posted, 1 = Pending confirmation. */
enum class EntryStatus(val code: Int) {
    /** Counted in the rollups, and therefore in every figure on screen. */
    POSTED(0),

    /**
     * Generated by a recurring rule and awaiting one tap to confirm.
     *
     * Excluded from the rollup triggers, so an unconfirmed entry never distorts
     * a budget bar. This is also the landing place a future SMS importer would
     * use for unverified transactions.
     */
    PENDING(1),
    ;

    companion object {
        fun fromCode(code: Int): EntryStatus = entries.firstOrNull { it.code == code }
            ?: error("unknown entry_status: $code")
    }
}

/** `frequency` — 0 = Monthly, 1 = Weekly, 2 = Yearly. P1, with recurring rules. */
enum class Frequency(val code: Int) {
    MONTHLY(0),
    WEEKLY(1),
    YEARLY(2),
    ;

    companion object {
        fun fromCode(code: Int): Frequency = entries.firstOrNull { it.code == code }
            ?: error("unknown frequency: $code")
    }
}

/** `rule_target` — 0 = Expense, 1 = Income. Enforced as an XOR by table CHECK. */
enum class RuleTarget(val code: Int) {
    EXPENSE(0),
    INCOME(1),
    ;

    companion object {
        fun fromCode(code: Int): RuleTarget = entries.firstOrNull { it.code == code }
            ?: error("unknown rule_target: $code")
    }
}

/**
 * What the app follows for light and dark — 04 §7's "theme" setting.
 *
 * Stored as a string rather than a code, because unlike every other enum here
 * this one is a preference rather than a column with a `CHECK`, and a readable
 * value in `app_meta` is worth more than two bytes.
 */
enum class ThemeChoice(val stored: String) {
    /** The default. A phone already set to dark has answered the question. */
    SYSTEM("system"),
    LIGHT("light"),
    DARK("dark"),
    ;

    companion object {
        fun fromStored(value: String?): ThemeChoice =
            entries.firstOrNull { it.stored == value } ?: SYSTEM
    }
}
